# Generated by Django 4.0.3 on 2022-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='currency',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
